import { describe, expect, test } from 'vite-plus/test';
import {
  clampAgentManagerZoomPercent,
  clampTerminalViewMode,
  createSessionAlias,
  createSessionRecord,
  DEFAULT_TERMINAL_SESSION_TITLE,
  getPreferredSessionTitle,
  getTerminalSessionSurfaceTitle,
  getSessionShortcutLabel,
  getVisiblePrimaryTitle,
  getVisibleTerminalTitle,
  isDefaultSessionSearchTitle,
  normalizeSessionRenameTitle,
  normalizeTerminalTitle,
} from './session-grid-contract-session';

describe('session shortcut labels', () => {
  test('should generate numeric default aliases from the display id', () => {
    expect(createSessionAlias(1, 0)).toBe('00');
    expect(createSessionAlias(2, 1)).toBe('01');
    expect(createSessionAlias(3, 2)).toBe('02');
    expect(createSessionAlias(101, 0)).toBe('00');
  });

  test('should format per-session shortcut text from the slot index', () => {
    expect(getSessionShortcutLabel(0, 'mac')).toBe('⌘⌥1');
    expect(getSessionShortcutLabel(5, 'mac')).toBe('⌘⌥6');
    expect(getSessionShortcutLabel(8, 'default')).toBe('Ctrl+Alt+9');
  });

});

describe('session surface titles', () => {
  test('should collapse autogenerated aliases to only the display id', () => {
    const terminalSession = createSessionRecord(18, 0, { displayId: '99' });

    expect(getTerminalSessionSurfaceTitle(terminalSession)).toBe('99');
  });

  test('should prefix renamed aliases with the display id', () => {
    const terminalSession = {
      ...createSessionRecord(18, 0, { displayId: '99' }),
      alias: 'Backend',
    };
    expect(getTerminalSessionSurfaceTitle(terminalSession)).toBe('99 Backend');
  });

  test('should prefer a custom title for terminal surface titles', () => {
    const terminalSession = {
      ...createSessionRecord(18, 0, { displayId: '99' }),
      alias: 'Backend',
      title: 'Bug Fixing',
    };
    expect(getTerminalSessionSurfaceTitle(terminalSession)).toBe('99. Bug Fixing');
  });
});

describe('agent manager zoom settings', () => {
  test('should clamp invalid zoom values to the supported range', () => {
    expect(clampAgentManagerZoomPercent(undefined)).toBe(100);
    expect(clampAgentManagerZoomPercent(49)).toBe(50);
    expect(clampAgentManagerZoomPercent(90.4)).toBe(90);
    expect(clampAgentManagerZoomPercent(95.6)).toBe(96);
    expect(clampAgentManagerZoomPercent(240)).toBe(200);
  });
});

describe('visible primary titles', () => {
  test('should normalize direct rename modal submissions into plain session titles', () => {
    expect(normalizeSessionRenameTitle(' \n • Build   ∗ logs\t#1!!! \n ')).toBe('Build logs #1!!!');
    expect(normalizeSessionRenameTitle('  Fix: API_retry (v2) / auth + tests  ')).toBe(
      'Fix: API_retry (v2) / auth + tests'
    );
    expect(normalizeSessionRenameTitle(' • ∗ \n ')).toBeUndefined();
  });

  test('should strip leading progress markers from terminal titles for supported agents', () => {
    expect(normalizeTerminalTitle('  ⠸ OpenAI Codex  ')).toBe('OpenAI Codex');
    expect(normalizeTerminalTitle('✳ Claude Code')).toBe('Claude Code');
    expect(normalizeTerminalTitle('✻ check-implementation-status')).toBe('check-implementation-status');
    expect(normalizeTerminalTitle('✦ demo-project')).toBe('demo-project');
    expect(normalizeTerminalTitle('◇ demo-project')).toBe('demo-project');
    expect(normalizeTerminalTitle('🤖 Copilot fix')).toBe('Copilot fix');
    expect(normalizeTerminalTitle('🔔 Copilot fix')).toBe('Copilot fix');
    expect(normalizeTerminalTitle('OC | Review repository')).toBe('Review repository');
    expect(normalizeTerminalTitle('⠸ OC | Review repository')).toBe('Review repository');
    expect(normalizeTerminalTitle('π - Implement Pi restore - ghostex')).toBe('Implement Pi restore');
    expect(normalizeTerminalTitle('⠸ π - Implement Pi restore - ghostex')).toBe('Implement Pi restore');
    expect(normalizeTerminalTitle('  π >   Delete marketplace skills   ')).toBe('Delete marketplace skills');
    expect(normalizeTerminalTitle('  π ⠧   Delete marketplace skills   ')).toBe('Delete marketplace skills');
  });

  test('should strip Antigravity CLI attention titles down to agy', () => {
    expect(normalizeTerminalTitle('🔔 agy')).toBe('agy');
    expect(normalizeTerminalTitle('agy')).toBe('agy');
    expect(getVisibleTerminalTitle('🔔 agy')).toBeUndefined();
    expect(getVisibleTerminalTitle('agy')).toBeUndefined();
  });

  test('should strip Cursor CLI working and ready status suffixes from terminal titles', () => {
    expect(normalizeTerminalTitle('Cursor Agent - ✅ Ready')).toBeUndefined();
    expect(normalizeTerminalTitle('Cursor Agent')).toBeUndefined();
    expect(getVisibleTerminalTitle('Cursor Agent - ✅ Ready')).toBeUndefined();
    expect(getVisibleTerminalTitle('Cursor Agent')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Cursor Agent - ✅ Ready')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Cursor Agent')).toBeUndefined();
    expect(normalizeTerminalTitle('My Task - ⏳ Working ···')).toBe('My Task');
    expect(normalizeTerminalTitle('My Task - ⏳ Working .··')).toBe('My Task');
    expect(normalizeTerminalTitle('My Task - ⏳ Working ..·')).toBe('My Task');
    expect(normalizeTerminalTitle('My Task - ✅ Ready')).toBe('My Task');
    expect(normalizeTerminalTitle('- ⏳ Working ..·')).toBeUndefined();
    expect(getVisibleTerminalTitle('My Task - ⏳ Working ···')).toBe('My Task');
    expect(getVisibleTerminalTitle('- ⏳ Working ..·')).toBeUndefined();
  });

  test('should hide generated Session N placeholder titles in sidebar items', () => {
    expect(getVisiblePrimaryTitle('Session 1')).toBeUndefined();
    expect(getVisiblePrimaryTitle(' Session 12 ')).toBeUndefined();
    expect(getVisiblePrimaryTitle(DEFAULT_TERMINAL_SESSION_TITLE)).toBeUndefined();
    expect(getVisiblePrimaryTitle('Codex Session')).toBeUndefined();
    expect(getVisiblePrimaryTitle('…/dev/_active/agent-tiler')).toBeUndefined();
    expect(getVisiblePrimaryTitle('Claude Code')).toBe('Claude Code');
  });

  test('should hide bare agent status word terminal titles', () => {
    expect(getVisibleTerminalTitle('Working')).toBeUndefined();
    expect(getVisibleTerminalTitle('Fix attention title filtering')).toBe('Fix attention title filtering');
  });

  test('should prefer the terminal title when choosing a visible session title', () => {
    expect(getPreferredSessionTitle('Session 1', 'Claude Code / repo sweep')).toBe('Claude Code / repo sweep');
  });

  test('should prefer Claude generated rename titles over numeric session card titles', () => {
    expect(getPreferredSessionTitle('00', '✳ check-implementation-status')).toBe('check-implementation-status');
  });

  test('should fall back to the custom session title when no terminal title exists', () => {
    expect(getPreferredSessionTitle('Bug Fix', undefined)).toBe('Bug Fix');
  });

  test('should ignore generic ghostex terminal titles when choosing a visible session title', () => {
    expect(getPreferredSessionTitle('Session 1', 'ghostex')).toBeUndefined();
  });

  test('should ignore placeholder and path-like terminal titles when choosing persisted titles', () => {
    expect(getPreferredSessionTitle(DEFAULT_TERMINAL_SESSION_TITLE, undefined)).toBeUndefined();
    expect(getPreferredSessionTitle('Codex Session', '…/dev/_active/agent-tiler')).toBeUndefined();
    expect(getPreferredSessionTitle('Bug Fix', '…/dev/_active/agent-tiler')).toBe('Bug Fix');
  });

  test('should ignore bare agent names when choosing a visible session title', () => {
    expect(getPreferredSessionTitle('Session 1', 'Codex')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Codex CLI')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Droid')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Factory Droid')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Grok')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Grok Build')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Amp')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Amp CLI')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Antigravity')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Antigravity CLI')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Cursor')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Cursor Agent')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Cursor CLI')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'OpenAI Codex')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'π - ghostex')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Claude')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', 'Claude Code')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', '  ⠸ Codex  ')).toBeUndefined();
    expect(getPreferredSessionTitle('Session 1', '  ✳ Claude Code  ')).toBeUndefined();
  });

  test('should ignore the default Windows PowerShell executable title', () => {
    expect(
      getPreferredSessionTitle('Session 1', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe')
    ).toBeUndefined();
  });

  test('should classify supported default agent session titles as search placeholders', () => {
    expect(isDefaultSessionSearchTitle('Pi Agent Session')).toBe(true);
    expect(isDefaultSessionSearchTitle('Codex Agent Session')).toBe(true);
    expect(isDefaultSessionSearchTitle('Cursor Agent Session')).toBe(true);
    expect(isDefaultSessionSearchTitle('Claude Code Agent Session')).toBe(true);
    expect(isDefaultSessionSearchTitle('Review Pi agent behavior')).toBe(false);
  });
});

describe('clampTerminalViewMode', () => {
  test('should default invalid modes to grid', () => {
    expect(clampTerminalViewMode('horizontal')).toBe('horizontal');
    expect(clampTerminalViewMode('vertical')).toBe('vertical');
    expect(clampTerminalViewMode('grid')).toBe('grid');
    expect(clampTerminalViewMode('diagonal')).toBe('grid');
    expect(clampTerminalViewMode(undefined)).toBe('grid');
  });
});
