//! `settings.md` and `hotkeys.md`: the catalog as Markdown for the Ghostex Help skill and `ghostex guide`.

use super::{catalog, CatalogEntry, ValueType, GENERATOR};
use crate::json::{ToJson, J};

fn format_default(value: Option<&J>) -> String {
    match value {
        Some(J::Str("")) => "(empty)".to_string(),
        Some(J::Str(text)) => text.to_string(),
        Some(value) => value.to_json().to_compact_string(),
        None => "undefined".to_string(),
    }
}

fn option_values(entry: &CatalogEntry) -> String {
    entry
        .options
        .iter()
        .map(|option| option.value.as_str())
        .collect::<Vec<_>>()
        .join(" | ")
}

fn describe_type(entry: &CatalogEntry) -> String {
    let default = format_default(entry.default);
    match entry.value_type {
        ValueType::Boolean => format!("boolean, default {default}"),
        ValueType::Enum => format!("one of {}; default {default}", option_values(entry)),
        ValueType::Number => {
            let range = entry
                .range
                .map(|range| {
                    let step = range
                        .step
                        .filter(|step| *step != 0.0)
                        .map(|step| format!(" step {}", crate::json::js_number_string(step)))
                        .unwrap_or_default();
                    format!(
                        " {} to {}{step}",
                        crate::json::js_number_string(range.min),
                        crate::json::js_number_string(range.max)
                    )
                })
                .unwrap_or_default();
            let allowed = if entry.options.is_empty() {
                String::new()
            } else {
                format!(" one of {};", option_values(entry))
            };
            format!("number{range}{allowed} default {default}")
        }
        ValueType::String => format!("text, default {default}"),
        ValueType::Json => {
            "structured value; change it in Settings, not with `ghostex settings set`".to_string()
        }
        ValueType::Ui => {
            "Settings UI row without a settings key; use `ghostex settings open`".to_string()
        }
    }
}

fn render_entry(entry: &CatalogEntry) -> String {
    let mut flags = Vec::new();
    if entry.advanced {
        flags.push("advanced");
    }
    if !entry.agent_writable && !matches!(entry.value_type, ValueType::Json | ValueType::Ui) {
        flags.push("not agent-writable");
    }
    let flag_text = if flags.is_empty() {
        String::new()
    } else {
        format!(" [{}]", flags.join(", "))
    };
    let labelled = entry.value_type == ValueType::Enum
        || (entry.value_type == ValueType::Number && !entry.options.is_empty());
    let option_labels = if labelled {
        entry
            .options
            .iter()
            .filter(|option| option.label != option.value)
            .map(|option| format!("{} = {}", option.value, option.label))
            .collect::<Vec<_>>()
            .join(", ")
    } else {
        String::new()
    };
    let option_text = if option_labels.is_empty() {
        String::new()
    } else {
        format!(" Option labels: {option_labels}.")
    };
    let platform_text: String = entry
        .platform_defaults
        .iter()
        .map(|(platform, value)| {
            format!(
                " Default on {}: {}.",
                crate::availability::platform_name(*platform),
                format_default(Some(value))
            )
        })
        .collect();
    let availability_text = entry
        .availability
        .as_ref()
        .map(|note| format!(" {note}"))
        .unwrap_or_default();
    format!(
        "- **{}** `{}` ({}){flag_text}: {}{option_text}{platform_text}{availability_text}",
        entry.title,
        entry.key,
        describe_type(entry),
        entry.subtitle
    )
}

/// `skills/ghostex-help/references/settings.md`.
pub fn settings_markdown() -> String {
    let catalog = catalog();
    let mut lines: Vec<String> = vec![
        "# Ghostex settings reference".into(),
        String::new(),
        format!("Generated by `{GENERATOR}` from the Settings catalog. Do not edit by hand; run `cargo xtask help-generate`."),
        String::new(),
        "How to use this file:".into(),
        String::new(),
        "- Every row is a Settings control. The backtick word is the settings key used by `ghostex settings get|set|reset <key>`.".into(),
        "- `ghostex settings list --json` prints the same catalog with the current values, so prefer it over reading this file when the app is available.".into(),
        "- Rows marked `not agent-writable`, `structured value`, or `Settings UI row` must be changed by the user in Settings. Open the right page with `ghostex settings open <key>`.".into(),
        "- The desktop app must be running for `set`; it applies the change exactly like a save in the Settings modal.".into(),
        String::new(),
    ];
    let mut current_tab = "";
    let mut current_group = "";
    let mut current_section = "";
    for entry in &catalog.settings {
        if entry.tab != current_tab {
            current_tab = &entry.tab;
            current_group = "";
            current_section = "";
            lines.push(format!("## {} (tab `{}`)", entry.tab_title, entry.tab));
            lines.push(String::new());
        }
        if let Some(group) = entry
            .group
            .as_deref()
            .filter(|group| *group != current_group)
        {
            current_group = group;
            current_section = "";
            lines.push(format!(
                "### {}",
                entry.group_title.as_deref().unwrap_or_default()
            ));
            lines.push(String::new());
        }
        if entry.section != current_section {
            current_section = &entry.section;
            let heading = if entry.group.is_some() { "####" } else { "###" };
            lines.push(format!("{heading} {}", entry.section_title));
            lines.push(String::new());
        }
        lines.push(render_entry(entry));
    }
    lines.push(String::new());
    let mut text = collapse_blank_lines(&lines.join("\n"));
    text.push('\n');
    trim_double_newline(text)
}

/// `skills/ghostex-help/references/hotkeys.md`.
pub fn hotkeys_markdown() -> String {
    let catalog = catalog();
    let mut lines: Vec<String> = vec![
        "# Ghostex hotkeys reference".into(),
        String::new(),
        format!("Generated by `{GENERATOR}` from the hotkey catalog. Do not edit by hand; run `cargo xtask help-generate`."),
        String::new(),
        "Default bindings are listed for macOS (`cmd`) with the Windows/Linux default where it differs. Users rebind them in Settings > Hotkeys, and agents change them with `ghostex settings hotkeys list`, `ghostex settings hotkeys set <id> <keys>` (`none` unassigns) and `ghostex settings hotkeys reset <id>|--all`; use the Id column below.".into(),
        String::new(),
        "| Action | Default | Windows/Linux | What it does | Id |".into(),
        "| --- | --- | --- | --- | --- |".into(),
    ];
    for hotkey in &catalog.hotkeys {
        let default_key = if hotkey.default_key.is_empty() {
            "unassigned".to_string()
        } else {
            format!("`{}`", hotkey.default_key)
        };
        let windows_linux_key = hotkey
            .windows_linux_default_key
            .filter(|key| !key.is_empty())
            .map(|key| format!("`{key}`"))
            .unwrap_or_default();
        lines.push(format!(
            "| {} | {default_key} | {windows_linux_key} | {} | `{}` |",
            hotkey.title,
            hotkey.description.replace('|', "\\|"),
            hotkey.id
        ));
    }
    lines.push(String::new());
    let mut text = lines.join("\n");
    text.push('\n');
    trim_double_newline(text)
}

/// `text.replace(/\n{3,}/gu, '\n\n')`.
fn collapse_blank_lines(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut newlines = 0;
    for character in text.chars() {
        if character == '\n' {
            newlines += 1;
            continue;
        }
        out.push_str(if newlines >= 2 {
            "\n\n"
        } else if newlines == 1 {
            "\n"
        } else {
            ""
        });
        newlines = 0;
        out.push(character);
    }
    out.push_str(if newlines >= 2 {
        "\n\n"
    } else if newlines == 1 {
        "\n"
    } else {
        ""
    });
    out
}

/// `text.replace(/\n\n$/u, '\n')`.
fn trim_double_newline(mut text: String) -> String {
    if text.ends_with("\n\n") {
        text.pop();
    }
    text
}
